[package]
name = "collo-ml"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
pest = "2.8"
pest_derive = "2.8"
thiserror.workspace = true
collomatique-ilp = { path = "../ilp" }
regex = "*"
collo-ml-derive = { path = "../collo-ml-derive" }